# Generated by Django 5.2.7 on 2025-10-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=11)),
                ("data_reserva", models.DateField()),
                ("horario_reserva", models.TimeField()),
                ("numero_mesa", models.IntegerField()),
                ("quantidade_adulto", models.IntegerField()),
                ("quantidade_criança", models.IntegerField()),
                ("data_criação", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
